"attribute vec4 a_position;\n"
"attribute vec2 a_texcoord;\n"
"attribute vec3 a_normal;\n"
"attribute vec4 a_color;\n"
"varying vec4 v_color;\n"
"varying vec3 v_normal;\n"
"varying vec2 v_texcoord;\n"
