"uniform mat4 u_m;\n"
"uniform mat4 u_mvp;\n"
"uniform mat3 u_model_inv_transp;\n"
"uniform mat4 u_v_inv;\n"
"uniform vec4 u_scene_ambient;\n"
"uniform vec4 u_color;\n"
"struct Material\n"
"{\n"
	"vec4 ambient;\n"
	"vec4 diffuse;\n"
	"vec4 specular;\n"
	"float shininess;\n"
"};\n"
"uniform Material u_material;\n"
"struct LightSource\n"
"{\n"
	"int type;\n"
	"vec3 position;\n"
	"vec4 diffuse;\n"
	"vec4 specular;\n"
	"float constantAttenuation;\n"
    "float linearAttenuation;\n"
    "float quadraticAttenuation;\n"
	"float spotCutoff;\n"
    "float spotExponent;\n"
	"vec3 spotDirection;\n"
"};\n"
"const int POINT_LIGHT = 0;\n"
"const int DIRECTIONAL_LIGHT = 1;\n"
"const int SPOT_LIGHT = 2;\n"
"uniform int u_numOfLights;\n"
"uniform LightSource u_light0;\n"
